### ISSUE TITLE
Performance of Algorithm...

### ISSUE THREAD

**Issue by AkshayChoulwar** [atherdon/gs-ml-nlp#12]
I am thinking that for classifying ingredients.... 

first we make set of diary items and whenever any items come we check the set and if value positive then we add it in category (if this is a requirement then why we need ML and NLP here) without ML also solution for this problem is possible

**Comment by atherdon** [comment]
there no innovation in simple programming
and just classifying - is only a first step on the road
first step in order to see if this can be useful

Just duplicating in order to have that here.

btw, maybe you right - so i don't know and maybe you don't know too - i mean we cannot find it out without trying :)

**Comment by atherdon** [comment]
but if you tell me - let's find another way - we'll sit down and find it

**Comment by AkshayChoulwar** [comment]
I implemented it using machine learning but still have to make modifications......

there are two advantages using Machine Leaning:

1.Once the model trained on testing it will take less time if our data is like(in GB)
2.If the user entered wrong spelling like for Butter and Buttered it will classify perfectly to dairy for both.

**Comment by atherdon** [comment]
So, what will be our next steps? you asked about sharing with you more
ingredients in order to test how your algorytm works and understand will it
find all dairy related, right?

about option 2 - perfect!
will check my other repos and find an advanced list of ingredients

**Comment by atherdon** [comment]
did i get you right - i need to convert this data, right : @atherdon/gs-ml-nlp#9?

**Comment by AkshayChoulwar** [comment]
Yes...convert it and update the ingredients. csv  (add other category data also)..we have only 110 ingredients in csv  file so far.

**Comment by atherdon** [comment]
ok, so i got it right.

**Comment by atherdon** [comment]
question: if i attach csv without category - will it be ok? i mean if i
place category 'undefinded'

**Comment by AkshayChoulwar** [comment]
Nope....we required csv for training and it should have label(category) so
that we can train it.

for testing phase it will be OK.

**Comment by atherdon** [comment]
ohh, right now i understand what you need exactly from me.
the easiest way for me is to export data from this link: https://airtable.com/shrmtzBGvND2be9GF/tbltaXhTFOl8FCdzV/viwscovAeDhZnk2Ae and add dairy as category, cause there only dairy items now. will it be ok as fast turn around?

**Comment by atherdon** [comment]
And i start realize that we need more data that i was prepared before...

**Comment by AkshayChoulwar** [comment]
Yes..

**Comment by atherdon** [comment]
i think it can be closed
