### ISSUE TITLE
Discussion with Puru

### ISSUE THREAD

**Issue by atherdon** [atherdon/gs-ml-nlp#21]
i think i shared a wrong file - ingredients & departments.
check this: https://raw.githubusercontent.com/GroceriStar/tensor-something/master/UGLResults.csv

**Comment by puru-kohli** [comment]
I should improve the model with the link you sent earlier, right? I have found some photos too and can convert them using online OCR

**Comment by atherdon** [comment]
yes

**Comment by atherdon** [comment]
@puru-kohli this is our new team member and he wants to tell you something.
@wael44 feel free
